const hambMenu = document.getElementById("hamb-menu");
let hambStatus = false; // false sta per 'Menu Chiuso'...

hambMenu.addEventListener("click", () => {
    if(!hambStatus) {
        // Menu Chiuso -> Aperto:
        hambMenu.classList.remove("close", "open");// Rimuovo la classe 'close' (se presente)...
        hambMenu.offsetWidth;// Forzo il reflow...
        hambMenu.classList.add("open");// Aggiungo la classe 'open'...
        hambStatus = true;
    } else {
        // Menu Aperto -> Chiuso:
        hambMenu.classList.remove("open");// Rimuovo la classe 'open' (se presente)...
        hambMenu.offsetWidth;// Forzo il reflow...
        hambMenu.classList.add("open", "close");
        hambStatus = false;
    }
});
